# Select optimization (-O or -g). -O will be automatically bumped up to the 
# highest level of optimization the compiler supports. If want something in
# between then specify the exact level you want, e.g., -O1 or -O2
OptLevel := -g

##############################################################################
# You should not need to edit below this line.
##############################################################################
# The location of the customized Makefiles
# also inherited from the parent Makefile
include ${MakefileDir}/Makefile.coin
include ${MakefileDir}/Makefile.location

IncDir := ${SbbIncDir} ${CglIncDir} ${OsiClpIncDir} ${OsiIncDir}
IncDir += ${ClpIncDir} ${CoinIncDir} ${bzlibIncDir} ${zlibIncDir}

LibDir := ${SbbLibDir} ${CglLibDir} ${OsiClpLibDir} ${OsiLibDir}
LibDir += ${ClpLibDir} ${CoinLibDir} ${bzlibLibDir} ${zlibLibDir}

LibName := ${SbbLibName} ${CglLibName} ${OsiClpLibName} ${OsiLibName} 
LibName += ${ClpLibName} ${CoinLibName} ${bzlibLibName} ${zlibLibName}

Define := ${SbbDefine} ${CglDefine} ${OsiClpDefine} ${OsiDefine} 
Define += ${ClpDefine} ${CoinDefine} ${bzlibDefine} ${zlibDefine}

##############################################################################
# You should not need to edit below this line.
##############################################################################

CXXFLAGS += $(OPTFLAG)
ifeq ($(OptLevel),-g)
    CXXFLAGS += -DSBB_DEBUG
endif

#use clp
CXXFLAGS += $(addprefix -D,COIN_USE_CLP)
#use osl
#CXXFLAGS += $(addprefix -D,COIN_USE_OSL)

TESTSRC := SbbMain.cpp
TESTSRC += unitTest.cpp

###############################################################################

space:= $(empty) $(empty)
OptVersion := $(subst $(space),_,$(OptLevel))

TARGETDIR := $(UNAME)$(OptVersion)
DEPDIR := dep

VPATH := . : include : Junk : ${TARGETDIR} : ${DEPDIR}

#########################################################################

CXXFLAGS += $(addprefix -I,${IncDir})
CXXFLAGS += $(addprefix -D,${Define})

LIBDIRS := ${LibDir}
LIBS    := ${LibName}

LDFLAGS := $(addprefix -L,$(LIBDIRS))
LDFLAGS += $(call ifprefix,$(SHLINKPREFIX),$(LIBDIRS))
LDFLAGS += $(patsubst lib%,-l%,$(basename $(LIBS)))

ifeq ($(findstring Linux,${UNAME}),Linux)
	CXXFLAGS +=	-DREADLINE
	LDFLAGS += -lhistory -lreadline -ltermcap
endif
#LDFLAGS += libefence

###############################################################################

TESTOBJ := $(addprefix $(TARGETDIR)/, $(TESTSRC:.cpp=.o))
TESTDEP := $(addprefix $(DEPDIR)/, $(TESTSRC:.cpp=.d))

###############################################################################
# This one must be right before the rules

include ${MakefileDir}/Makefile.rules

###############################################################################

.DELETE_ON_ERROR:

.PHONY: unitTest

unitTest: $(TARGETDIR)/sbb

$(TARGETDIR)/sbb : $(TESTOBJ)
	@rm -rf Junk
	@echo ""
	@echo Creating sbb
	@mkdir -p $(TARGETDIR)
	@rm -f $@
	$(CXX) $(CXXFLAGS) -o $@ $(TESTOBJ) $(LDFLAGS) $(SYSLD) -lm
	${CP} $@ ..

###############################################################################

%::
	@mkdir -p Junk
	touch Junk/$(notdir $@)

###############################################################################

-include $(TESTDEP)
