lib_objects =                       \
                                    \
             ArrayJOR.$(obj_suffix) \
         ArrayListJOR.$(obj_suffix) \
                  Att.$(obj_suffix) \
              AttBldr.$(obj_suffix) \
           AttBldrCOR.$(obj_suffix) \
               AttCOR.$(obj_suffix) \
             BomEntry.$(obj_suffix) \
          BomEntryCOR.$(obj_suffix) \
             BopEntry.$(obj_suffix) \
          BopEntryCOR.$(obj_suffix) \
          CTVecSupply.$(obj_suffix) \
            CaseToken.$(obj_suffix) \
         CaseTokenCOR.$(obj_suffix) \
            Component.$(obj_suffix) \
         ComponentCOR.$(obj_suffix) \
         ComponentJOR.$(obj_suffix) \
          Coordinator.$(obj_suffix) \
       CoordinatorCOR.$(obj_suffix) \
               Demand.$(obj_suffix) \
            DemandCOR.$(obj_suffix) \
     ExceptionHandler.$(obj_suffix) \
           JavaAccObj.$(obj_suffix) \
        JavaAccObjCOR.$(obj_suffix) \
            JniClient.$(obj_suffix) \
           JniHandler.$(obj_suffix) \
           MessageMgr.$(obj_suffix) \
        MessageMgrCOR.$(obj_suffix) \
            Operation.$(obj_suffix) \
         OperationCOR.$(obj_suffix) \
                 Part.$(obj_suffix) \
              PartCOR.$(obj_suffix) \
           PggHandler.$(obj_suffix) \
     PreJavaException.$(obj_suffix) \
              Problem.$(obj_suffix) \
           ProblemCOR.$(obj_suffix) \
           ScalarAtts.$(obj_suffix) \
            StringJOR.$(obj_suffix) \
            StringVec.$(obj_suffix) \
           Substitute.$(obj_suffix) \
        SubstituteCOR.$(obj_suffix) \
                Utils.$(obj_suffix) \
           VectorAtts.$(obj_suffix) \

