# This Makefile is here to tell you not to do makes from this directory
all:
	echo Do not do make in the src directory.  CD to some platform directory first.

wit:
	echo Do not do make in the src directory.  CD to some platform directory first.

libwit.a:
	echo Do not do make in the src directory.  CD to some platform directory first.
