lib_objects = \
        ApiCall.$(obj_suffix) \
        ApiMgr.$(obj_suffix) \
        AvailSched.$(obj_suffix) \
        BillEntry.$(obj_suffix) \
        BomEntry.$(obj_suffix) \
        BopEntry.$(obj_suffix) \
        BoundSet.$(obj_suffix) \
        BuildAhd.$(obj_suffix) \
        CompMgr.$(obj_suffix) \
        Component.$(obj_suffix) \
        CpxParSpec.$(obj_suffix) \
        DataRead.$(obj_suffix) \
        DataWrit.$(obj_suffix) \
        Demand.$(obj_suffix) \
        DetCons.$(obj_suffix) \
        DetImpOP.$(obj_suffix) \
        DetOptImpMgr.$(obj_suffix) \
        DetVars.$(obj_suffix) \
        Entity.$(obj_suffix) \
        EqAll.$(obj_suffix) \
        ExtOptMgr.$(obj_suffix) \
        FSS.$(obj_suffix) \
        FeasChkr.$(obj_suffix) \
        FlexVec.$(obj_suffix) \
        GlobalComp.$(obj_suffix) \
        HeurAll.$(obj_suffix) \
        HeurAtor.$(obj_suffix) \
        HeurImp.$(obj_suffix) \
        HeurModifier.$(obj_suffix) \
        List.$(obj_suffix) \
        Mapping.$(obj_suffix) \
        MatCap.$(obj_suffix) \
        Misc.$(obj_suffix) \
        MrpExp.$(obj_suffix) \
        MultiEx.$(obj_suffix) \
        MultiObj.$(obj_suffix) \
        MultiRoute.$(obj_suffix) \
        NodeSorter.$(obj_suffix) \
        ObjVec.$(obj_suffix) \
        OffsetProc.$(obj_suffix) \
        Operation.$(obj_suffix) \
        OptComp.$(obj_suffix) \
        OptMisc.$(obj_suffix) \
        OptProblem.$(obj_suffix) \
        Param.$(obj_suffix) \
        ParamMgr.$(obj_suffix) \
        Parlex.$(obj_suffix) \
        Part.$(obj_suffix) \
        Pegging.$(obj_suffix) \
        PenExec.$(obj_suffix) \
        PipBuilder.$(obj_suffix) \
        PipMgr.$(obj_suffix) \
        PipPartReqMgr.$(obj_suffix) \
        PipPgg.$(obj_suffix) \
        PipReq.$(obj_suffix) \
        PipReqMgr.$(obj_suffix) \
        Post.$(obj_suffix) \
        Pre.$(obj_suffix) \
        PreHelp.$(obj_suffix) \
        Problem.$(obj_suffix) \
        PropRtg.$(obj_suffix) \
        PtrMap.$(obj_suffix) \
        PtrSched.$(obj_suffix) \
        RealArg.$(obj_suffix) \
        Repos.$(obj_suffix) \
        Routing.$(obj_suffix) \
        RtAn.$(obj_suffix) \
        SaeMgr.$(obj_suffix) \
        ScenAtt.$(obj_suffix) \
        ScenAttMgr.$(obj_suffix) \
        Scenario.$(obj_suffix) \
        Schedule.$(obj_suffix) \
        SelSplit.$(obj_suffix) \
        SelStRe.$(obj_suffix) \
        Selection.$(obj_suffix) \
        Selector.$(obj_suffix) \
        Session.$(obj_suffix) \
        SglSrcMgr.$(obj_suffix) \
        SglSrcSite.$(obj_suffix) \
        SolnWrit.$(obj_suffix) \
        SolverIf.$(obj_suffix) \
        StCons.$(obj_suffix) \
        StVars.$(obj_suffix) \
        Stack.$(obj_suffix) \
        Stage.$(obj_suffix) \
        StochImpMgr.$(obj_suffix) \
        StochMode.$(obj_suffix) \
        StochOpt.$(obj_suffix) \
        SubEntry.$(obj_suffix) \
        SymTable.$(obj_suffix) \
        Timing.$(obj_suffix) \
        Util.$(obj_suffix) \
        VecBS.$(obj_suffix) \
        Vecs.$(obj_suffix) \
        WitRun.$(obj_suffix) \
        api.$(obj_suffix) \
        bomApi.$(obj_suffix) \
        bopApi.$(obj_suffix) \
        demApi.$(obj_suffix) \
        globApi.$(obj_suffix) \
        msgApi.$(obj_suffix) \
        opnApi.$(obj_suffix) \
        optApi.$(obj_suffix) \
        partApi.$(obj_suffix) \
        stochApi.$(obj_suffix) \
        subApi.$(obj_suffix) \
        witLexer.$(obj_suffix) \
        witParse.$(obj_suffix) \

