#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "cl-wit-ap-c-ws"
#
# Compiles and links a WIT application program in C.
# This version is for the Windows SDK platform.
# Argument: $1 = program name (no suffix)
#------------------------------------------------------------------------------

rm $1.exe 2> /dev/null

cl $1.c -Za -EHs -nologo -I$WIT_HOME/wit/src $WIT_HOME/wit/winsdk/wit.lib

if [ -f $1.exe ]
then

   echo
   echo "Compilation and linking of $1.exe was successful."
   echo

else

   echo
   echo "Compilation and linking of $1.exe has failed."
   echo

fi
