#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "cl-wit-cpx-ap-c++-ws".
#
# Compiles and links a WIT application program in C++ that also invokes CPLEX.
# This version is for the Windows SDK platform.
# Argument: $1 = program name (no suffix)
#------------------------------------------------------------------------------

rm $1.exe 2> /dev/null

if [ "$WIT_CPLEX_LIB_SUBDIR" = "" ]
then

   WIT_CPLEX_LIB_SUBDIR=x86_windows_vs2010/stat_mta

fi 

CPLEX_LIB=$WIT_CPLEX_HOME/lib/$WIT_CPLEX_LIB_SUBDIR/cplex124.lib

cl                                  \
  -Tp                               \
   $1.C                             \
  -Za                               \
  -EHs                              \
  -nologo                           \
  -I$WIT_HOME/wit/src               \
  -I$WIT_CPLEX_HOME/include/ilcplex \
    $WIT_HOME/wit/winsdk/wit.lib    \
    $CPLEX_LIB                      \


echo

if [ -f $1.exe ]
then

   echo "Compilation and linking of $1.exe was successful."

else

   echo "Compilation and linking of $1.exe has failed."

fi

echo
