#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "cl-wit-cpx-ap-c++".
#
# Compiles and links a WIT application program in C++ that also invokes CPLEX.
# Argument: $1 = program name (no suffix)
#------------------------------------------------------------------------------

if [ "$PLATFORM" = "winsdk" ]
then

   cl-wit-cpx-ap-c++-ws $1

   exit

fi

. set-vars-cl-wit-ap

rm $1   2> /dev/null
rm $1.o 2> /dev/null

$COMP_CPP                           \
  -g                                \
  -c                                \
   $1.C                             \
  -I$WIT_HOME/wit/src               \
  -I$WIT_CPLEX_HOME/include/ilcplex \


if [ ! -f $1.o ]
then

   echo
   echo "Compilation of $1.C has failed."
   echo

   exit

fi

$LINK                                     \
  -g                                      \
  -L$WIT_HOME/wit/$PLATFORM               \
  -L$WIT_CPLEX_HOME/lib/$CPLEX_LIB_SUBDIR \
   $1.o                                   \
  -lwit                                   \
  -lcplex                                 \
  -ldl                                    \
  -o                                      \
   $1                                     \


rm $1.o

if [ -f $1 ]
then

   echo
   echo "Compilation and linking of $1 was successful."
   echo

else

   echo
   echo "Linking of $1 has failed."
   echo

fi
