#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "cl-wit-jni-so-c++".
#
# Compiles and links a C++ shared object that invokes WIT and JNI.
# Argument: $1 = shared object name (no suffix)
#
# This is script is implemented for the Linux platform only.
#------------------------------------------------------------------------------

rm lib$1.so 2> /dev/null
rm    $1.o  2> /dev/null

#---------
# Compile:
#---------

g++ $1.C -I$WIT_HOME/wit/src -I$JAVA_HOME/include -c -fPIC

#------
# Link:
#------

g++ -shared $1.o -L$WIT_HOME/wit/linux -lwit -lm -o lib$1.so

rm    $1.o  2> /dev/null
