#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "cl-wit-ap-c"
#
# Compiles and links a WIT application program in C.
# Argument: $1 = program name (no suffix)
#------------------------------------------------------------------------------

if [ "$PLATFORM" = "winsdk" ]
then

   cl-wit-ap-c-ws $1

   exit

fi

. set-vars-cl-wit-ap

rm $1   2> /dev/null
rm $1.o 2> /dev/null

$COMP_C -g -c $1.c -I$WIT_HOME/wit/src

if [ ! -f $1.o ]
then

   echo
   echo "Compilation of $1.c has failed."
   echo

   exit

fi

$LINK -g -L$WIT_HOME/wit/$PLATFORM $1.o -lwit -ldl -o $1

rm $1.o

if [ -f $1 ]
then

   echo
   echo "Compilation and linking of $1 was successful."
   echo

else

   echo
   echo "Linking of $1 has failed."
   echo

fi
