#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script "set-vars-cl-wit-ap"
#
# Sets environment variables for building WIT application programs.
# To be called with ".".
# Not to be called on winsdk.
#------------------------------------------------------------------------------

if [ "$PLATFORM" = "linux" ]
then

             COMP_C="gcc"
           COMP_CPP="g++"
               LINK="g++ -pthread -lcoinglpk -lcoinlapack -lcoinmumps"
   CPLEX_LIB_SUBDIR=x86-64_linux/static_pic

elif [ "$PLATFORM" = "zlinux64" ]
then

             COMP_C="gcc -m64"
           COMP_CPP="g++ -m64"
               LINK="g++ -pthread"
   CPLEX_LIB_SUBDIR=s390x_sles10_4.1/static_pic

elif [ "$PLATFORM" = "power64v5" ]
then

             COMP_C="xlC128 -q64"
           COMP_CPP="xlC128 -q64"
               LINK="xlC128 -q64 -lpthreads -bmaxdata:0x06FFFFFFFFFFFFF8"
   CPLEX_LIB_SUBDIR=power64_aix5.3_9.0/static_mt_stl

elif [ "$PLATFORM" = "winsdk" ]
then

   echo
   echo "ERROR: Script set-vars-cl-wit-ap was invoked with PLATFORM=winsdk."
   echo
   echo "Script aborted."
   echo

   exit

else

   echo
   echo "ERROR: Unsupported value of the PLATFORM environment variable."
   echo "   PLATFORM = \"$PLATFORM\""
   echo
   echo "   Supported values for PLATFORM:"
   echo "      \"linux\""
   echo "      \"zlinux64\""
   echo "      \"power64v5\""
   echo "      \"winsdk\""
   echo
   echo "Script aborted."
   echo

   exit

fi
