#!/bin/sh

#----------------------------------------------------------------
# Sh Script wit-api-test.
#
# Tests WIT using API function calls.
#----------------------------------------------------------------

echo
echo "Running the WIT API test."
echo

cd $WIT_HOME/wit/api-test

rm api-out-new.txt 2> /dev/null

#-----------------
# Test with apiAll
#-----------------

echo "Building apiAll."

echo "--------------------"     2>&1 | cat >> api-out-new.txt
echo "Testing with apiAll."     2>&1 | cat >> api-out-new.txt
echo "--------------------"     2>&1 | cat >> api-out-new.txt

cl-wit-ap-c apiAll              2>&1 | cat >> api-out-new.txt

echo "Running  apiAll."

export  API_ALL_COIN_REQ="Embedded"
export API_ALL_CPLEX_REQ="Embedded"
   #
   # These variable settings tell apiAll to require a build of WIT with
   # COIN embedded and CPLEX embedded.

./apiAll                        2>&1 | cat >> api-out-new.txt

#-----------------
# Test with msgAll
#-----------------

echo "Building msgAll."

echo "--------------------"     2>&1 | cat >> api-out-new.txt
echo "Testing with msgAll."     2>&1 | cat >> api-out-new.txt
echo "--------------------"     2>&1 | cat >> api-out-new.txt

cl-wit-ap-c++ msgAll            2>&1 | cat >> api-out-new.txt

echo "Running  msgAll."

./msgAll                        2>&1 | cat >> api-out-new.txt

#---------------------
# Test with extOptTest
#---------------------

echo "Building extOptTest."

echo "------------------------" 2>&1 | cat >> api-out-new.txt
echo "Testing with extOptTest." 2>&1 | cat >> api-out-new.txt
echo "------------------------" 2>&1 | cat >> api-out-new.txt

cl-wit-cpx-ap-c++ extOptTest    2>&1 | cat >> api-out-new.txt

echo "Running  extOptTest."

./extOptTest                    2>&1 | cat >> api-out-new.txt

#------------------
# Test with errTest
#------------------

echo "Building errTest."

echo "---------------------"    2>&1 | cat >> api-out-new.txt
echo "Testing with errTest."    2>&1 | cat >> api-out-new.txt
echo "---------------------"    2>&1 | cat >> api-out-new.txt

cl-wit-ap-c++ errTest           2>&1 | cat >> api-out-new.txt

echo "Running  errTest."

#-------------------------------------------------------------------------------
# Note that some case numbers are skipped.
# In particular, cases 7 & 8 are skipped from this test, because they test WIT's
# behavior when it runs out of memory and this kind of test can be very slow in
# some environments.
#-------------------------------------------------------------------------------

./errTest  1                    2>&1 | cat >> api-out-new.txt
./errTest  2                    2>&1 | cat >> api-out-new.txt
./errTest  3                    2>&1 | cat >> api-out-new.txt
./errTest  4                    2>&1 | cat >> api-out-new.txt
./errTest  5                    2>&1 | cat >> api-out-new.txt
./errTest  9                    2>&1 | cat >> api-out-new.txt
./errTest 10                    2>&1 | cat >> api-out-new.txt
./errTest 11                    2>&1 | cat >> api-out-new.txt
./errTest 12                    2>&1 | cat >> api-out-new.txt
./errTest 13                    2>&1 | cat >> api-out-new.txt
./errTest 14                    2>&1 | cat >> api-out-new.txt
./errTest 15                    2>&1 | cat >> api-out-new.txt
./errTest 16                    2>&1 | cat >> api-out-new.txt
./errTest 17                    2>&1 | cat >> api-out-new.txt
./errTest 18                    2>&1 | cat >> api-out-new.txt
./errTest 19                    2>&1 | cat >> api-out-new.txt
./errTest 20                    2>&1 | cat >> api-out-new.txt
./errTest 22                    2>&1 | cat >> api-out-new.txt
./errTest 23                    2>&1 | cat >> api-out-new.txt
./errTest 24                    2>&1 | cat >> api-out-new.txt
./errTest 25                    2>&1 | cat >> api-out-new.txt
./errTest 26                    2>&1 | cat >> api-out-new.txt
./errTest 27                    2>&1 | cat >> api-out-new.txt
./errTest 28                    2>&1 | cat >> api-out-new.txt
./errTest 29                    2>&1 | cat >> api-out-new.txt
./errTest 30                    2>&1 | cat >> api-out-new.txt
./errTest 31                    2>&1 | cat >> api-out-new.txt
./errTest 32                    2>&1 | cat >> api-out-new.txt
./errTest 33                    2>&1 | cat >> api-out-new.txt
./errTest 34                    2>&1 | cat >> api-out-new.txt
./errTest 35                    2>&1 | cat >> api-out-new.txt
./errTest 36                    2>&1 | cat >> api-out-new.txt
./errTest 37                    2>&1 | cat >> api-out-new.txt
./errTest 38                    2>&1 | cat >> api-out-new.txt
./errTest 39                    2>&1 | cat >> api-out-new.txt
./errTest 40                    2>&1 | cat >> api-out-new.txt
./errTest 41                    2>&1 | cat >> api-out-new.txt
./errTest 42                    2>&1 | cat >> api-out-new.txt
./errTest 43                    2>&1 | cat >> api-out-new.txt
./errTest 44                    2>&1 | cat >> api-out-new.txt
./errTest 45                    2>&1 | cat >> api-out-new.txt
./errTest 46                    2>&1 | cat >> api-out-new.txt
./errTest 47                    2>&1 | cat >> api-out-new.txt
./errTest 48                    2>&1 | cat >> api-out-new.txt
./errTest 49                    2>&1 | cat >> api-out-new.txt
./errTest 50                    2>&1 | cat >> api-out-new.txt
./errTest 51                    2>&1 | cat >> api-out-new.txt
./errTest 52                    2>&1 | cat >> api-out-new.txt
./errTest 53                    2>&1 | cat >> api-out-new.txt
./errTest 54                    2>&1 | cat >> api-out-new.txt
./errTest 55                    2>&1 | cat >> api-out-new.txt
./errTest 56                    2>&1 | cat >> api-out-new.txt
./errTest 57                    2>&1 | cat >> api-out-new.txt
./errTest 58                    2>&1 | cat >> api-out-new.txt
./errTest 59                    2>&1 | cat >> api-out-new.txt
./errTest 60                    2>&1 | cat >> api-out-new.txt
./errTest 61                    2>&1 | cat >> api-out-new.txt
./errTest 62                    2>&1 | cat >> api-out-new.txt
./errTest 63                    2>&1 | cat >> api-out-new.txt
./errTest 64                    2>&1 | cat >> api-out-new.txt
./errTest 65                    2>&1 | cat >> api-out-new.txt
./errTest 66                    2>&1 | cat >> api-out-new.txt
./errTest 67                    2>&1 | cat >> api-out-new.txt
./errTest 68                    2>&1 | cat >> api-out-new.txt
./errTest 69                    2>&1 | cat >> api-out-new.txt
./errTest 70                    2>&1 | cat >> api-out-new.txt
./errTest 71                    2>&1 | cat >> api-out-new.txt

#-------------------------
# Compare to saved output.
#-------------------------

if [ "$PLATFORM" = "winsdk" ]
then

   unix2dos -q api-out-new.txt

fi

echo
echo "Comparing api-out-new.txt with api-out-$PLATFORM.txt."
echo

diff                                        \
  -I "^Build Date:"                         \
  -I "^Run Started At:"                     \
  -I "^         Build Date:"                \
  -I "^         Run Started At:"            \
                                            \
   api-out-$PLATFORM.txt                    \
   api-out-new.txt                          \
 > api-out-diff.txt                         \


if [ -s api-out-diff.txt ]
then

   echo "Significant differences were found. See:"
   echo
   echo "   $WIT_HOME/wit/api-test/api-out-diff.txt"
   echo
   echo "The WIT API test was unsuccessful."
   echo

else

   echo "No significant differences were found."
   echo
   echo "The WIT API test was successful."
   echo

fi
