#!/bin/sh

#----------------------------------------------------------------
# Sh Script wit-no-cplex-test.
#
# Tests WIT without CPLEX embedded.
#
# This script is implemented for the Linux platform only.
#----------------------------------------------------------------

if [ "$PLATFORM" != "linux" ]
then

   echo
   echo "ERROR: Script wit-no-cplex-test was invoked with PLATFORM=$PLATFORM."
   echo "       This script is implemented for the linux platform only."
   echo
   echo "Script aborted."
   echo

   exit

fi

echo
echo "Running the WIT No-CPLEX test."
echo

cd $WIT_HOME/wit/api-test

rm no-cplex-out-new.txt 2> /dev/null

echo "Building apiAll."

cl-wit-ap-c apiAll 2>&1 | cat >> no-cplex-out-new.txt

echo "Running  apiAll."

./apiAll           2>&1 | cat >> no-cplex-out-new.txt

echo
echo "Comparing no-cplex-out-new.txt with no-cplex-out-linux.txt."
echo

diff                             \
  -I "^Build Date:"              \
  -I "^Run Started At:"          \
  -I "^         Build Date:"     \
  -I "^         Run Started At:" \
   no-cplex-out-linux.txt        \
   no-cplex-out-new.txt          \
 > no-cplex-out-diff.txt         \


if [ -s no-cplex-out-diff.txt ]
then

   echo "Significant differences were found. See:"
   echo
   echo "   $WIT_HOME/wit/api-test/no-cplex-out-diff.txt"
   echo
   echo "The WIT No-CPLEX test was unsuccessful."
   echo

else

   echo "No significant differences were found."
   echo
   echo "The WIT No-CPLEX test was successful."
   echo

fi
