#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-sel-split
#
# Performs the WIT selection splitting test, unless $1 = "save".
# If $1 = "save", this script saves the results of the selection splitting test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Selection Splitting" $1

wit-test-case sel-split/case01 heur-spl3 $1
wit-test-case sel-split/case02 heur-spl3 $1
wit-test-case sel-split/case03 heur-spl3 $1
wit-test-case sel-split/case04 heur-spl3 $1
wit-test-case sel-split/case05 heur-spl3 $1
wit-test-case sel-split/case06 heur-spl3 $1
wit-test-case sel-split/case07 heur-spl3 $1
wit-test-case sel-split/case08 heur-spl3 $1
wit-test-case sel-split/case09 heur-spl3 $1
wit-test-case sel-split/case10 heur-spl3 $1
wit-test-case sel-split/case11 heur-spl3 $1
wit-test-case sel-split/case12 heur-spl3 $1
wit-test-case sel-split/case13 heur-spl3 $1
wit-test-case sel-split/case14 heur-spl3 $1
wit-test-case sel-split/case15 heur-spl3 $1
wit-test-case sel-split/case16 twmebd    $1
wit-test-case sel-split/case17 heur-spl3 $1
wit-test-case sel-split/case18 heur-spl3 $1
wit-test-case sel-split/case19 heur-spl3 $1
wit-test-case sel-split/case20 heur-spl3 $1
wit-test-case sel-split/case21 heur-spl3 $1
wit-test-case sel-split/case22 heur-spl3 $1
wit-test-case sel-split/case23 heur-spl3 $1
wit-test-case sel-split/case24 heur-spl3 $1
wit-test-case sel-split/case25 heur-spl3 $1
wit-test-case sel-split/case26 heur-spl3 $1
wit-test-case sel-split/case27 heur-spl3 $1
wit-test-case sel-split/case28 heur-spl3 $1
wit-test-case sel-split/case29 heur-spl3 $1
wit-test-case sel-split/case31 heur-spl3 $1
wit-test-case sel-split/case32 heur-spl3 $1
wit-test-case sel-split/case33 heur-spl3 $1
wit-test-case sel-split/case34 heur-spl3 $1
wit-test-case sel-split/case35 heur-spl3 $1
wit-test-case sel-split/case36 heur-spl3 $1
wit-test-case sel-split/case37 heur-spl3 $1
wit-test-case sel-split/case38 heur-spl3 $1
wit-test-case sel-split/case39 heur-spl3 $1
