#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-int
#
# Performs the WIT integrality test, unless $1 = "save".
# If $1 = "save", this script saves the results of the integrality test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Integrality" $1

wit-test-case int/case1a soln $1
wit-test-case int/case1b soln $1
wit-test-case int/case1c soln $1
wit-test-case int/case1d soln $1
wit-test-case int/case1e soln $1
wit-test-case int/case2  soln $1
wit-test-case int/case3  eval $1
wit-test-case int/case4  soln $1
wit-test-case int/case5  soln $1
wit-test-case int/case6  soln $1
wit-test-case int/case7  soln $1
