#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-pip-opo
#
# Performs the WIT PIP, Old Pegging Order test, unless $1 = "save".
# If $1 = "save", this script saves the results of the PIP, Old Pegging Order
# test.
#------------------------------------------------------------------------------

wit-test-cap-heading "PIP, Old Pegging Order" $1

wit-test-case gpip/case08 pip-opo      $1
wit-test-case gpip/case10 pip-opo      $1
wit-test-case gpip/case11 pip-opo      $1
wit-test-case gpip/case12 pip-opo      $1
wit-test-case gpip/case13 pip-opo      $1
wit-test-case gpip/case14 pip-opo      $1
wit-test-case gpip/case15 pip-opo      $1
wit-test-case gpip/case16 pip-opo      $1
wit-test-case gpip/case17 pip-opo      $1
wit-test-case gpip/case18 pip-opo      $1
wit-test-case gpip/case19 pip-opo      $1
wit-test-case gpip/case20 pip-opo-eval $1
wit-test-case gpip/case21 pip-opo      $1
wit-test-case gpip/case22 pip-opo      $1
wit-test-case gpip/case23 pip-opo      $1
wit-test-case gpip/case24 pip-opo      $1
wit-test-case gpip/case25 pip-opo-opt  $1
wit-test-case gpip/case26 pip-opo      $1

wit-test-case  pip/case08 pip-opo      $1
wit-test-case  pip/case09 pip-opo      $1
wit-test-case  pip/case10 pip-opo      $1
wit-test-case  pip/case11 pip-opo      $1
wit-test-case  pip/case12 pip-opo      $1
wit-test-case  pip/case13 pip-opo      $1
wit-test-case  pip/case14 pip-opo      $1
wit-test-case  pip/case15 pip-opo      $1
wit-test-case  pip/case16 pip-opo      $1
wit-test-case  pip/case17 pip-opo      $1
wit-test-case  pip/case18 pip-opo      $1
wit-test-case  pip/case19 pip-opo      $1
wit-test-case  pip/case20 pip-opo      $1
wit-test-case  pip/case21 pip-opo      $1
wit-test-case  pip/case22 pip-opo      $1
wit-test-case  pip/case23 pip-opo      $1
wit-test-case  pip/case24 pip-opo      $1
wit-test-case  pip/case25 pip-opo      $1
wit-test-case  pip/case26 pip-opo-opt  $1
wit-test-case  pip/case27 pip-opo-eval $1
wit-test-case  pip/case28 pip-opo-eval $1
wit-test-case  pip/case29 pip-opo      $1
wit-test-case  pip/case30 pip-opo      $1
wit-test-case  pip/case31 pip-opo      $1
wit-test-case  pip/case32 pip-opo      $1
wit-test-case  pip/case34 pip-opo      $1
wit-test-case  pip/case35 pip-opo      $1
wit-test-case  pip/case36 pip-opo      $1
wit-test-case  pip/case38 pip-opo-eval $1
wit-test-case  pip/case39 pip-opo      $1
wit-test-case  pip/case40 pip-opo      $1
wit-test-case  pip/case41 pip-opo      $1
wit-test-case  pip/case42 pip-opo      $1
wit-test-case  pip/case43 pip-opo      $1
wit-test-case  pip/case44 pip-opo      $1
wit-test-case  pip/case45 pip-opo      $1
wit-test-case  pip/case46 pip-opo      $1
wit-test-case  pip/case47 pip-opo      $1
wit-test-case  pip/case48 pip-opo      $1
wit-test-case  pip/case49 pip-opo      $1
wit-test-case  pip/case51 pip-opo      $1
wit-test-case  pip/case52 pip-opo      $1
wit-test-case  pip/case67 pip-opo      $1
