#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-clp-cbc
#
# Performs the WIT CLP/CBC invocation test, unless $1 = "save".
# If $1 = "save", this script saves the results of the CLP/CBC invocation test.
#------------------------------------------------------------------------------

wit-test-cap-heading "CLP/CBC Invocation" $1

wit-test-case clp-cbc/case1  heur-opt $1
wit-test-case clp-cbc/case1  soln     $1
wit-test-case clp-cbc/case1  crit     $1
wit-test-case clp-cbc/case1  mps      $1
wit-test-case clp-cbc/case2  soln     $1
wit-test-case clp-cbc/case3  soln     $1
wit-test-case clp-cbc/case4  soln     $1
wit-test-case clp-cbc/case5  soln     $1
wit-test-case clp-cbc/case6  opt-prt  $1
