#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-multi-obj
#
# Performs the WIT multiple objectives test, unless $1 = "save".
# If $1 = "save", this script saves the results of the multiple objectives
# test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Multiple Objectives" $1

wit-test-case multi-obj/case01 opt-prt $1
wit-test-case multi-obj/case02 opt-prt $1
wit-test-case multi-obj/case03 opt-prt $1
wit-test-case multi-obj/case04 opt-prt $1
wit-test-case multi-obj/case05 opt-prt $1
wit-test-case multi-obj/case06 opt-prt $1
wit-test-case multi-obj/case07 opt-prt $1
wit-test-case multi-obj/case08 opt-prt $1
wit-test-case multi-obj/case09 opt-prt $1
wit-test-case multi-obj/case10 opt-prt $1
wit-test-case multi-obj/case11 opt-prt $1
wit-test-case multi-obj/case12 opt-prt $1
wit-test-case multi-obj/case13 opt-prt $1
wit-test-case multi-obj/case14 opt-prt $1
wit-test-case multi-obj/case15 opt-prt $1
wit-test-case multi-obj/case16 opt-prt $1
wit-test-case multi-obj/case17 opt-prt $1
wit-test-case multi-obj/case18 opt-prt $1
