#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-ship-late
#
# Performs the WIT ship late allowed test, unless $1 = "save".
# If $1 = "save", this script saves the results of the ship late allowed test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Ship Late Allowed" $1

wit-test-case ship-late/case1 soln      $1
wit-test-case ship-late/case1 heur-soln $1
wit-test-case ship-late/case2 pre-prt   $1
wit-test-case ship-late/case3 soln      $1
wit-test-case ship-late/case4 soln      $1
