#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-two-lev-lot
#
# Performs the WIT two-level lot sizes test, unless $1 = "save".
# If $1 = "save", this script saves the results of the two-level lot sizes test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Two-Level Lot Sizes" $1

wit-test-case two-lev-lot/case1 eval      $1
wit-test-case two-lev-lot/case2 eval      $1
wit-test-case two-lev-lot/case3 heur-soln $1
wit-test-case two-lev-lot/case4 heur-soln $1
wit-test-case two-lev-lot/case4  mrp-soln $1
wit-test-case two-lev-lot/case5 heur-soln $1
