#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-prop-rtg
#
# Performs the WIT proportionate routing test, unless $1 = "save".
# If $1 = "save", this script saves the results of the proportionate routing
# test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Proportionate Routing" $1

wit-test-case prop-rtg/case01 heur-spl3 $1
wit-test-case prop-rtg/case02 heur-spl3 $1
wit-test-case prop-rtg/case03 heur-spl3 $1
wit-test-case prop-rtg/case04 heur-spl3 $1
wit-test-case prop-rtg/case05 heur-spl3 $1
wit-test-case prop-rtg/case06 heur-spl3 $1
wit-test-case prop-rtg/case07 heur-spl3 $1
wit-test-case prop-rtg/case08 heur-spl3 $1
wit-test-case prop-rtg/case09 heur-spl3 $1
wit-test-case prop-rtg/case10 heur-spl3 $1
wit-test-case prop-rtg/case11 heur-spl3 $1
wit-test-case prop-rtg/case12 heur-spl3 $1
wit-test-case prop-rtg/case13 heur-spl3 $1
wit-test-case prop-rtg/case14 heur-spl3 $1
wit-test-case prop-rtg/case15 heur-spl3 $1
wit-test-case prop-rtg/case16 heur-spl3 $1
wit-test-case prop-rtg/case17 heur-spl3 $1
wit-test-case prop-rtg/case18 heur-spl3 $1
wit-test-case prop-rtg/case19 heur-spl3 $1
wit-test-case prop-rtg/case20 heur-spl3 $1
wit-test-case prop-rtg/case21 heur-spl3 $1
wit-test-case prop-rtg/case22 heur-spl3 $1
wit-test-case prop-rtg/case23 heur-spl3 $1
wit-test-case prop-rtg/case24 heur-spl3 $1
wit-test-case prop-rtg/case25 heur-spl3 $1
wit-test-case prop-rtg/case26 heur-spl3 $1
wit-test-case prop-rtg/case27 heur-spl3 $1
wit-test-case prop-rtg/case28 heur-spl3 $1
wit-test-case prop-rtg/case29 heur-spl3 $1
wit-test-case prop-rtg/case30 heur-spl3 $1
wit-test-case prop-rtg/case31 heur-spl3 $1
wit-test-case prop-rtg/case32 heur-spl3 $1
wit-test-case prop-rtg/case33 heur-spl3 $1
wit-test-case prop-rtg/case34 heur-spl3 $1
wit-test-case prop-rtg/case35 heur-spl3 $1
wit-test-case prop-rtg/case36 heur-spl3 $1
wit-test-case prop-rtg/case37 heur-spl3 $1
wit-test-case prop-rtg/case38 heur-spl3 $1
wit-test-case prop-rtg/case39 heur-spl3 $1
wit-test-case prop-rtg/case40 heur-spl3 $1
wit-test-case prop-rtg/case41 heur-spl3 $1
wit-test-case prop-rtg/case42 heur-spl3 $1
wit-test-case prop-rtg/case43 heur-spl3 $1
wit-test-case prop-rtg/case44 heur-spl3 $1
wit-test-case prop-rtg/case45 heur-spl3 $1
wit-test-case prop-rtg/case46 heur-spl3 $1
