#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-pip
#
# Performs the WIT PIP test, unless $1 = "save".
# If $1 = "save", this script saves the results of the PIP test.
#------------------------------------------------------------------------------

wit-test-cap-heading "PIP" $1

wit-test-case gpip/case08 pip      $1
wit-test-case gpip/case10 pip      $1
wit-test-case gpip/case11 pip      $1
wit-test-case gpip/case12 pip      $1
wit-test-case gpip/case13 pip      $1
wit-test-case gpip/case14 pip      $1
wit-test-case gpip/case15 pip      $1
wit-test-case gpip/case16 pip      $1
wit-test-case gpip/case17 pip      $1
wit-test-case gpip/case18 pip      $1
wit-test-case gpip/case19 pip      $1
wit-test-case gpip/case20 pip-eval $1
wit-test-case gpip/case21 pip      $1
wit-test-case gpip/case22 pip      $1
wit-test-case gpip/case23 pip      $1
wit-test-case gpip/case24 pip      $1
wit-test-case gpip/case25 pip-opt  $1
wit-test-case gpip/case26 pip      $1

wit-test-case  pip/case08 pip      $1
wit-test-case  pip/case09 pip      $1
wit-test-case  pip/case10 pip      $1
wit-test-case  pip/case11 pip      $1
wit-test-case  pip/case12 pip      $1
wit-test-case  pip/case13 pip      $1
wit-test-case  pip/case14 pip      $1
wit-test-case  pip/case15 pip      $1
wit-test-case  pip/case16 pip      $1
wit-test-case  pip/case17 pip      $1
wit-test-case  pip/case18 pip      $1
wit-test-case  pip/case19 pip      $1
wit-test-case  pip/case20 pip      $1
wit-test-case  pip/case21 pip      $1
wit-test-case  pip/case22 pip      $1
wit-test-case  pip/case23 pip      $1
wit-test-case  pip/case24 pip      $1
wit-test-case  pip/case25 pip      $1
wit-test-case  pip/case26 pip-opt  $1
wit-test-case  pip/case27 pip-eval $1
wit-test-case  pip/case28 pip-eval $1
wit-test-case  pip/case29 pip      $1
wit-test-case  pip/case30 pip      $1
wit-test-case  pip/case31 pip      $1
wit-test-case  pip/case32 pip      $1
wit-test-case  pip/case34 pip      $1
wit-test-case  pip/case35 pip      $1
wit-test-case  pip/case36 pip      $1
wit-test-case  pip/case38 pip-eval $1
wit-test-case  pip/case39 pip      $1
wit-test-case  pip/case40 pip      $1
wit-test-case  pip/case41 pip      $1
wit-test-case  pip/case42 pip      $1
wit-test-case  pip/case43 pip      $1
wit-test-case  pip/case44 pip      $1
wit-test-case  pip/case45 pip      $1
wit-test-case  pip/case46 pip      $1
wit-test-case  pip/case47 pip      $1
wit-test-case  pip/case48 pip      $1
wit-test-case  pip/case49 pip      $1
wit-test-case  pip/case50 pip      $1
wit-test-case  pip/case51 pip      $1
wit-test-case  pip/case52 pip      $1
wit-test-case  pip/case53 pip      $1
wit-test-case  pip/case54 pip      $1
wit-test-case  pip/case55 pip      $1
wit-test-case  pip/case56 pip      $1
wit-test-case  pip/case57 pip      $1
wit-test-case  pip/case59 pip      $1
wit-test-case  pip/case60 pip      $1
wit-test-case  pip/case61 pip      $1
wit-test-case  pip/case62 pip      $1
wit-test-case  pip/case63 pip      $1
wit-test-case  pip/case64 pip      $1
wit-test-case  pip/case65 pip      $1
wit-test-case  pip/case66 pip      $1
wit-test-case  pip/case67 pip      $1
wit-test-case  pip/case68 pip      $1
wit-test-case  pip/case69 pip      $1
wit-test-case  pip/case70 pip      $1
wit-test-case  pip/case71 pip      $1
