#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-heur-search-inc
#
# Performs the WIT heuristic search increment test, unless $1 = "save".
# If $1 = "save", this script saves the results of the heuristic search
# increment test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Heuristic Search Increment" $1

wit-test-case heur-search-inc/case1a heur-soln $1
wit-test-case heur-search-inc/case1b heur-soln $1
wit-test-case heur-search-inc/case2  heur-soln $1
wit-test-case heur-search-inc/case3a heur-soln $1
wit-test-case heur-search-inc/case3b heur-soln $1
wit-test-case heur-search-inc/case4  heur-soln $1
