#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-multi-route
#
# Performs the WIT multi-route test, unless $1 = "save".
# If $1 = "save", this script saves the results of the multi-route test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Multi-Route" $1

wit-test-case multi-route/case01  heur-spl3 $1
wit-test-case multi-route/case02  heur-spl3 $1
wit-test-case multi-route/case03  heur-spl3 $1
wit-test-case multi-route/case04  heur-spl3 $1
wit-test-case multi-route/case05  heur-spl3 $1
wit-test-case multi-route/case06  heur-spl3 $1
wit-test-case multi-route/case07  heur-spl3 $1
wit-test-case multi-route/case08  heur-spl3 $1
wit-test-case multi-route/case08a heur-spl3 $1
wit-test-case multi-route/case09  heur-spl3 $1
wit-test-case multi-route/case10  heur-spl3 $1
wit-test-case multi-route/case11  heur-spl3 $1
wit-test-case multi-route/case12  heur-spl3 $1
wit-test-case multi-route/case13  heur-spl3 $1
wit-test-case multi-route/case13a heur-spl3 $1
wit-test-case multi-route/case13b heur-spl3 $1
wit-test-case multi-route/case14  heur-spl3 $1
wit-test-case multi-route/case15  heur-spl3 $1
wit-test-case multi-route/case16  heur-spl3 $1
wit-test-case multi-route/case17  heur-spl3 $1
wit-test-case multi-route/case18  heur-spl3 $1
wit-test-case multi-route/case19  heur-spl3 $1
wit-test-case multi-route/case20  heur-spl3 $1
wit-test-case multi-route/case21  heur-spl3 $1
wit-test-case multi-route/case22  heur-spl3 $1
wit-test-case multi-route/case23  heur-spl3 $1
wit-test-case multi-route/case24  heur-spl3 $1
wit-test-case multi-route/case25  heur-spl3 $1
