#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-pgd-crit
#
# Performs the WIT pegged critical list test, unless $1 = "save".
# If $1 = "save", this script saves the results of the pegged critical list
# test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Pegged Critical List" $1

wit-test-case pgd-crit/case1 heur-spl3-crit $1
wit-test-case pgd-crit/case2 heur-spl3-crit $1
wit-test-case pgd-crit/case3 heur-spl3-crit $1
wit-test-case pgd-crit/case4 heur-spl3-crit $1
wit-test-case pgd-crit/case5 heur-spl3-crit $1
