#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-stoch
#
# Performs the WIT stochastic implosion test, unless $1 = "save".
# If $1 = "save", this script saves the results of the stochastic implosion
# test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Stochastic Implosion" $1

wit-test-case stoch/case01 stoch $1
wit-test-case stoch/case01 soln  $1
wit-test-case stoch/case02 stoch $1
wit-test-case stoch/case03 stoch $1
wit-test-case stoch/case04 stoch $1
wit-test-case stoch/case05 stoch $1
wit-test-case stoch/case06 stoch $1
wit-test-case stoch/case07 stoch $1
wit-test-case stoch/case08 stoch $1
wit-test-case stoch/case09 stoch $1
wit-test-case stoch/case10 stoch $1
wit-test-case stoch/case11 stoch $1
wit-test-case stoch/case12 stoch $1
wit-test-case stoch/case14 stoch $1
wit-test-case stoch/case15 stoch $1
wit-test-case stoch/case16 stoch $1
wit-test-case stoch/case17 stoch $1
wit-test-case stoch/case18 stoch $1
wit-test-case stoch/case19 stoch $1
wit-test-case stoch/case20 stoch $1
wit-test-case stoch/case21 stoch $1
wit-test-case stoch/case22 stoch $1
wit-test-case stoch/case23 stoch $1
wit-test-case stoch/case24 stoch $1
wit-test-case stoch/case25 stoch $1
wit-test-case stoch/case26 stoch $1
wit-test-case stoch/case27 stoch $1
wit-test-case stoch/case28 stoch $1
wit-test-case stoch/case29 stoch $1
wit-test-case stoch/case30 stoch $1
wit-test-case stoch/case31 stoch $1
wit-test-case stoch/case32 stoch $1
wit-test-case stoch/case33 stoch $1
wit-test-case stoch/case34 stoch $1
wit-test-case stoch/case35 stoch $1
wit-test-case stoch/case36 stoch $1
wit-test-case stoch/case37 stoch $1
wit-test-case stoch/case38 stoch $1
wit-test-case stoch/case39 stoch $1
wit-test-case stoch/case40 stoch $1
wit-test-case stoch/case42 stoch $1
wit-test-case stoch/case43 stoch $1
wit-test-case stoch/case44 stoch $1
wit-test-case stoch/case45 stoch $1
wit-test-case stoch/case46 stoch $1
wit-test-case stoch/case47 stoch $1
wit-test-case stoch/case48 stoch $1
wit-test-case stoch/case49 stoch $1
wit-test-case stoch/case50 stoch $1
wit-test-case stoch/case51 stoch $1
wit-test-case stoch/case52 stoch $1
wit-test-case stoch/case53 stoch $1
wit-test-case stoch/case54 stoch $1
wit-test-case stoch/case55 stoch $1
wit-test-case stoch/case56 stoch $1
wit-test-case stoch/case57 stoch $1
wit-test-case stoch/case58 stoch $1
wit-test-case stoch/case59 stoch $1
wit-test-case stoch/case60 stoch $1
wit-test-case stoch/case61 stoch $1
wit-test-case stoch/case62 stoch $1
wit-test-case stoch/case63 stoch $1
wit-test-case stoch/case64 stoch $1
