#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-case-shiw
#
# Like wit-test-case-run, but the output is sent to the screen.
#------------------------------------------------------------------------------

PARAM_FILE=$WIT_HOME/wit-sa-test/params/$2.par

if [ ! -f $PARAM_FILE ]
then

   echo "ERROR:"
   echo "   The paramater file"
   echo "   $PARAM_FILE"
   echo "   does not exist."

   exit

fi

DATA_DIR=$WIT_HOME/wit-sa-test/data/$1

if [ ! -d $DATA_DIR ]
then

   echo "ERROR:"
   echo "   The data directory"
   echo "   $DATA_DIR"
   echo "   does not exist."
   exit

fi

cd $DATA_DIR

if [ ! -d $2 ]
then

   rm $2 2> /dev/null

   mkdir $2

fi

cd $2

rm -r output-new 2> /dev/null

mkdir output-new
cd    output-new

cp $PARAM_FILE .

$WIT_HOME/wit/$PLATFORM/wit $2.par
