#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-user-heur-start
#
# Performs the WIT user-specified heuristic starting solution test, unless
# $1 = "save".
# If $1 = "save", this script saves the results of the user-specified heuristic
# starting solution test.
#------------------------------------------------------------------------------

wit-test-cap-heading "User-Specified Heuristic Starting Solution" $1

wit-test-case user-heur-start/case01 heur-pia $1
wit-test-case user-heur-start/case02 heur-pia $1
wit-test-case user-heur-start/case03 heur-pia $1
wit-test-case user-heur-start/case04 heur-pia $1
wit-test-case user-heur-start/case05 heur-pia $1
wit-test-case user-heur-start/case06 heur-pia $1
wit-test-case user-heur-start/case07 heur-pia $1
