#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-mip
#
# Performs the WIT MIP test, unless $1 = "save".
# If $1 = "save", this script saves the results of the MIP test.
#------------------------------------------------------------------------------

wit-test-cap-heading "MIP Mode" $1

wit-test-case mip/case1a soln $1
wit-test-case mip/case1b soln $1
wit-test-case mip/case1c soln $1
wit-test-case mip/case1d soln $1
wit-test-case mip/case1e soln $1
wit-test-case mip/case2  soln $1
wit-test-case mip/case3  eval $1
wit-test-case mip/case4  soln $1
wit-test-case mip/case6  soln $1
wit-test-case mip/case7  soln $1

wit-test-case mip/case1a coin $1
wit-test-case mip/case1b coin $1
wit-test-case mip/case2  coin $1
wit-test-case mip/case6  coin $1
wit-test-case mip/case7  coin $1
