#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-sgl-src
#
# Performs the WIT single-source test, unless $1 = "save".
# If $1 = "save", this script saves the results of the single-source test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Single-Source" $1

wit-test-case sgl-src/case01 heur-spl3 $1
wit-test-case sgl-src/case02 heur-spl3 $1
wit-test-case sgl-src/case03 heur-spl3 $1
wit-test-case sgl-src/case04 heur-spl3 $1
wit-test-case sgl-src/case05 heur-spl3 $1
wit-test-case sgl-src/case06 heur-spl3 $1
wit-test-case sgl-src/case07 heur-spl3 $1
wit-test-case sgl-src/case08 heur-spl3 $1
wit-test-case sgl-src/case09 heur-spl3 $1
wit-test-case sgl-src/case10 heur-spl3 $1
wit-test-case sgl-src/case11 heur-spl3 $1
wit-test-case sgl-src/case12 heur-spl3 $1
wit-test-case sgl-src/case13 heur-spl3 $1
wit-test-case sgl-src/case14 heur-spl3 $1
wit-test-case sgl-src/case15 heur-spl3 $1
wit-test-case sgl-src/case16 heur-spl3 $1
wit-test-case sgl-src/case17 heur-spl3 $1
wit-test-case sgl-src/case18 heur-spl3 $1
wit-test-case sgl-src/case19 heur-spl3 $1
wit-test-case sgl-src/case20 heur-spl3 $1
wit-test-case sgl-src/case21 heur-spl3 $1
wit-test-case sgl-src/case22 heur-spl3 $1
wit-test-case sgl-src/case23 heur-spl3 $1
wit-test-case sgl-src/case24 heur-spl3 $1
wit-test-case sgl-src/case25 heur-spl3 $1
wit-test-case sgl-src/case26 heur-spl3 $1
wit-test-case sgl-src/case27 heur-spl3 $1
wit-test-case sgl-src/case28 heur-spl3 $1
wit-test-case sgl-src/case29 heur-spl3 $1
wit-test-case sgl-src/case30 heur-spl3 $1
wit-test-case sgl-src/case31 heur-spl3 $1
wit-test-case sgl-src/case32 heur-spl3 $1
wit-test-case sgl-src/case33 heur-spl3 $1
wit-test-case sgl-src/case34 heur-spl3 $1
wit-test-case sgl-src/case35 heur-spl3 $1
