#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-case
#
# Takes one of two possible actions regarding a single run of the WIT stand
# alone executable for test purposes.
#
# * If $3 is empty or != "save":
#   * Runs the WIT stand-alone executable.
#   * Displays the significant differences between the new output and the saved
#     output for the case being run.
#
# * If $3 = "save":
#   * Saves the results of the indicated run.
#
# Parameters:
#    $1: The subdirectory of $WIT_HOME/wit-sa-test/data in which the input
#        data file, wit.data, is to be found.
#    $2: The stem of the name of the parameters file.
#        The parameters file will be at: $WIT_HOME/wit-sa-test/params/$2.par
#------------------------------------------------------------------------------

if [ "$3" = "save" ]
then

   wit-test-case-save $1 $2

else

   wit-test-case-run  $1 $2
   wit-test-case-diff $1 $2

fi
