#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-misc
#
# Performs the WIT miscellaneous capabilities test, unless $1 = "save".
# If $1 = "save", this script saves the results of the miscellaneous
# capabilities test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Miscellaneous Capabilities" $1

wit-test-case standard/obj1 heur-soln  $1
wit-test-case standard/obj1 soln       $1

wit-test-case misc/case01   heur-pia   $1
wit-test-case misc/case02   heur-spl3  $1
wit-test-case misc/case03   heur-spl3  $1
wit-test-case misc/case05   write-data $1
wit-test-case misc/case06   heur-soln  $1
wit-test-case misc/case07   heur-soln  $1
wit-test-case misc/case08   pre-prt    $1
wit-test-case misc/case09   soln       $1
wit-test-case misc/case10   heur-spl3  $1
wit-test-case misc/case11   heur-spl3  $1
wit-test-case misc/case12   default    $1
wit-test-case misc/case13   default    $1
wit-test-case misc/case14   heur-soln  $1
wit-test-case misc/case15   pre-prt    $1
