#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-all
#
# Performs the WIT Stand-Alone Test, unless $1 = "save".
# If $1 = "save", this script saves the results of the WIT Stand-Alone Test.
#
# NOTE: This test is set up for the winsdk platform only.
#------------------------------------------------------------------------------

wit-test-multi-route     $1
wit-test-nstn            $1
wit-test-asap            $1
wit-test-multi-exec      $1
wit-test-old-stock-re    $1
wit-test-sel-stock-re    $1
wit-test-prop-rtg        $1
wit-test-pen-exec        $1
wit-test-sel-split       $1
wit-test-pen-exec-split  $1
wit-test-sgl-src         $1
wit-test-sel-rec         $1

wit-test-stock-bds       $1
wit-test-two-lev-lot     $1
wit-test-user-heur-start $1
wit-test-con-peg         $1
wit-test-pgd-crit        $1
wit-test-heur-search-inc $1
wit-test-lead-time-bds   $1

wit-test-mip             $1
wit-test-scrap           $1
wit-test-stoch           $1
wit-test-cplex           $1
wit-test-coin            $1
wit-test-multi-obj-cplex $1
wit-test-multi-obj-coin  $1

wit-test-ship-late       $1
wit-test-pip             $1
wit-test-pip-opo         $1
wit-test-misc            $1
