#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-stock-bds
#
# Performs the WIT stock bounds test, unless $1 = "save".
# If $1 = "save", this script saves the results of the stock bounds test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Stock Bounds" $1

wit-test-case stock-bounds/case01 heur-spl3    $1
wit-test-case stock-bounds/case02 heur-spl3    $1
wit-test-case stock-bounds/case03 heur-spl3    $1
wit-test-case stock-bounds/case04 heur-spl3    $1
wit-test-case stock-bounds/case05 heur-spl3    $1
wit-test-case stock-bounds/case06 heur-spl3    $1
wit-test-case stock-bounds/case07 heur-spl3    $1
wit-test-case stock-bounds/case08 heur-spl3    $1
wit-test-case stock-bounds/case09 heur-spl3    $1
wit-test-case stock-bounds/case10 heur-spl3    $1

wit-test-case stock-bounds/case01 heur-spl3-sr $1
wit-test-case stock-bounds/case02 heur-spl3-sr $1
wit-test-case stock-bounds/case03 heur-spl3-sr $1
wit-test-case stock-bounds/case04 heur-spl3-sr $1
wit-test-case stock-bounds/case05 heur-spl3-sr $1
wit-test-case stock-bounds/case06 heur-spl3-sr $1
wit-test-case stock-bounds/case07 heur-spl3-sr $1
wit-test-case stock-bounds/case08 heur-spl3-sr $1
wit-test-case stock-bounds/case09 heur-spl3-sr $1
wit-test-case stock-bounds/case10 heur-spl3-sr $1
