#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-pen-exec
#
# Performs the WIT penalized execution test, unless $1 = "save".
# If $1 = "save", this script saves the results of the penalized execution test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Penalized Execution" $1

wit-test-case pen-exec/case01 heur-spl3 $1
wit-test-case pen-exec/case02 heur-spl3 $1
wit-test-case pen-exec/case03 heur-spl3 $1
wit-test-case pen-exec/case04 heur-spl3 $1
wit-test-case pen-exec/case05 heur-spl3 $1
wit-test-case pen-exec/case06 heur-spl3 $1
wit-test-case pen-exec/case07 heur-spl3 $1
wit-test-case pen-exec/case08 heur-spl3 $1
wit-test-case pen-exec/case09 heur-spl3 $1
wit-test-case pen-exec/case10 heur-spl3 $1
wit-test-case pen-exec/case11 heur-spl3 $1
wit-test-case pen-exec/case12 heur-spl3 $1
wit-test-case pen-exec/case13 heur-spl3 $1
wit-test-case pen-exec/case14 heur-spl3 $1
wit-test-case pen-exec/case15 heur-spl3 $1
wit-test-case pen-exec/case16 heur-spl3 $1
wit-test-case pen-exec/case17 heur-spl3 $1
wit-test-case pen-exec/case18 heur-spl3 $1
wit-test-case pen-exec/case19 heur-spl3 $1
wit-test-case pen-exec/case20 heur-spl3 $1
wit-test-case pen-exec/case21 heur-spl3 $1
wit-test-case pen-exec/case22 heur-spl3 $1
wit-test-case pen-exec/case23 heur-spl3 $1
wit-test-case pen-exec/case24 heur-spl3 $1
wit-test-case pen-exec/case25 heur-spl3 $1
wit-test-case pen-exec/case26 heur-spl3 $1
wit-test-case pen-exec/case27 heur-spl3 $1
wit-test-case pen-exec/case28 heur-spl3 $1
wit-test-case pen-exec/case29 heur-spl3 $1
wit-test-case pen-exec/case30 heur-spl3 $1
wit-test-case pen-exec/case31 heur-spl3 $1
wit-test-case pen-exec/case32 heur-spl3 $1
wit-test-case pen-exec/case33 heur-spl3 $1
wit-test-case pen-exec/case34 heur-spl3 $1
wit-test-case pen-exec/case35 heur-spl3 $1
