#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-pen-exec-split
#
# Performs the WIT selection splitting for penalized execution test, unless
# $1 = "save".
# If $1 = "save", this script saves the results of the selection splitting for
# penalized execution test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Selection Splitting For Penalized Execution" $1

wit-test-case pen-exec-split/case01 heur-spl3 $1
wit-test-case pen-exec-split/case02 heur-spl3 $1
wit-test-case pen-exec-split/case03 heur-spl3 $1
wit-test-case pen-exec-split/case04 heur-spl3 $1
wit-test-case pen-exec-split/case05 heur-spl3 $1
wit-test-case pen-exec-split/case06 heur-spl3 $1
wit-test-case pen-exec-split/case07 heur-spl3 $1
wit-test-case pen-exec-split/case08 heur-spl3 $1
wit-test-case pen-exec-split/case09 heur-spl3 $1
wit-test-case pen-exec-split/case10 heur-spl3 $1
wit-test-case pen-exec-split/case11 heur-spl3 $1
wit-test-case pen-exec-split/case12 heur-spl3 $1
wit-test-case pen-exec-split/case13 heur-spl3 $1
wit-test-case pen-exec-split/case14 heur-spl3 $1
wit-test-case pen-exec-split/case15 heur-spl3 $1
wit-test-case pen-exec-split/case16 heur-spl3 $1
wit-test-case pen-exec-split/case17 heur-spl3 $1
wit-test-case pen-exec-split/case18 heur-spl3 $1
wit-test-case pen-exec-split/case19 heur-spl3 $1
wit-test-case pen-exec-split/case20 heur-spl3 $1
wit-test-case pen-exec-split/case21 heur-spl3 $1
wit-test-case pen-exec-split/case22 heur-spl3 $1
wit-test-case pen-exec-split/case23 heur-spl3 $1
wit-test-case pen-exec-split/case24 heur-spl3 $1
wit-test-case pen-exec-split/case25 heur-spl3 $1
wit-test-case pen-exec-split/case26 heur-spl3 $1
wit-test-case pen-exec-split/case27 heur-spl3 $1
wit-test-case pen-exec-split/case28 heur-spl3 $1
wit-test-case pen-exec-split/case29 heur-spl3 $1
wit-test-case pen-exec-split/case30 heur-spl3 $1
wit-test-case pen-exec-split/case31 heur-spl3 $1
wit-test-case pen-exec-split/case32 heur-spl3 $1
wit-test-case pen-exec-split/case33 heur-spl3 $1
wit-test-case pen-exec-split/case34 heur-spl3 $1
wit-test-case pen-exec-split/case35 heur-spl3 $1
wit-test-case pen-exec-split/case36 heur-spl3 $1
wit-test-case pen-exec-split/case37 heur-spl3 $1
wit-test-case pen-exec-split/case38 heur-spl3 $1
wit-test-case pen-exec-split/case39 heur-spl3 $1
wit-test-case pen-exec-split/case40 heur-spl3 $1
wit-test-case pen-exec-split/case41 heur-spl3 $1
wit-test-case pen-exec-split/case42 heur-spl3 $1
wit-test-case pen-exec-split/case43 heur-spl3 $1
wit-test-case pen-exec-split/case44 heur-spl3 $1
wit-test-case pen-exec-split/case46 heur-spl3 $1
wit-test-case pen-exec-split/case48 heur-spl3 $1
wit-test-case pen-exec-split/case49 heur-spl3 $1
