#!/bin/ksh


#------------------------------------------------------------------------------
# Script wit-test-case-save
#
# Saves the results of a single run of the WIT stand alone executable for test
# purposes.
# Log files are not saved.
# (CPLEX produces log files, whose contents can vary.
#  By default, RTC ignores log files.)
#
# Parameters:
#    $1: The subdirectory of $WIT_HOME/wit-sa-test/data in which the input
#        data file, wit.data, is to be found.
#    $2: The stem of the name of the parameters file.
#------------------------------------------------------------------------------

if [ ! -d $WIT_HOME/wit-sa-test/data/$1/$2/output-new ]
then

   echo "Save not done: Directory data/$1/$2/output-new does not exist."

   exit

fi

cd $WIT_HOME/wit-sa-test/data/$1/$2

rm -r output-new/*.log 2> /dev/null
rm -r output-sav       2> /dev/null

mv output-new output-sav
