#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-scrap
#
# Performs the WIT scrap allowed test, unless $1 = "save".
# If $1 = "save", this script saves the results of the scrap allowed test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Scrap Allowed" $1

wit-test-case scrap/case1 soln $1
wit-test-case scrap/case2 soln $1
wit-test-case scrap/case3 soln $1
