#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-multi-exec
#
# Performs the WIT multi-exec test, unless $1 = "save".
# If $1 = "save", this script saves the results of the multi-exec test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Multi-Exec" $1

wit-test-case multi-exec/case01 heur-spl3 $1
wit-test-case multi-exec/case02 heur-spl3 $1
wit-test-case multi-exec/case03 heur-spl3 $1
wit-test-case multi-exec/case04 heur-spl3 $1
wit-test-case multi-exec/case05 heur-spl3 $1
wit-test-case multi-exec/case06 heur-spl3 $1
wit-test-case multi-exec/case07 heur-spl3 $1
wit-test-case multi-exec/case08 twmebd    $1
wit-test-case multi-exec/case09 twmebd    $1
wit-test-case multi-exec/case10 twmebd    $1
wit-test-case multi-exec/case11 twmebd    $1
wit-test-case multi-exec/case12 heur-spl3 $1
wit-test-case multi-exec/case13 twmebd    $1
wit-test-case multi-exec/case14 twmebd    $1
wit-test-case multi-exec/case15 heur-spl3 $1
wit-test-case multi-exec/case16 heur-spl3 $1
