#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-sel-stock-re
#
# Performs the WIT selective stock reallocation test, unless $1 = "save".
# If $1 = "save", this script saves the results of the selective stock
# reallocation test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Selective Stock Reallocation" $1

wit-test-case sel-stock-re/case01 heur-spl3 $1
wit-test-case sel-stock-re/case02 heur-spl3 $1
wit-test-case sel-stock-re/case03 heur-spl3 $1
wit-test-case sel-stock-re/case04 heur-spl3 $1
wit-test-case sel-stock-re/case05 heur-spl3 $1
wit-test-case sel-stock-re/case06 heur-spl3 $1
wit-test-case sel-stock-re/case07 heur-spl3 $1
wit-test-case sel-stock-re/case08 heur-spl3 $1
wit-test-case sel-stock-re/case09 heur-spl3 $1
wit-test-case sel-stock-re/case10 heur-spl3 $1
wit-test-case sel-stock-re/case11 heur-spl3 $1
wit-test-case sel-stock-re/case12 heur-spl3 $1
wit-test-case sel-stock-re/case13 heur-spl3 $1
wit-test-case sel-stock-re/case14 heur-spl3 $1
wit-test-case sel-stock-re/case15 heur-spl3 $1
wit-test-case sel-stock-re/case16 heur-spl3 $1
