#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-cap-heading
#
# Prints the heading for the WIT SA Capability Test whose name is given by $1.
# If $2 = "save", a heading for saving the results of the test is printed.
#------------------------------------------------------------------------------

if [ "$2" = "save" ]
then

   echo "Saving Test Results: $1"

else

   echo "_______________________________________________________"
   echo
   echo "Test of $1"
   echo "_______________________________________________________"

fi
