#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-cplex
#
# Performs the WIT CPLEX invocation test, unless $1 = "save".
# If $1 = "save", this script saves the results of the CPLEX invocation test.
#------------------------------------------------------------------------------

wit-test-cap-heading "CPLEX Invocation" $1

wit-test-case cplex/case1  heur-opt $1
wit-test-case cplex/case1  crit     $1
wit-test-case cplex/case5  soln     $1
wit-test-case cplex/case6  stoch    $1
wit-test-case cplex/case7  soln     $1
wit-test-case cplex/case8  soln     $1
wit-test-case cplex/case9  soln     $1
wit-test-case cplex/case10 soln     $1
wit-test-case cplex/case11 soln     $1
wit-test-case cplex/case12 soln     $1
wit-test-case cplex/case13 soln     $1
wit-test-case cplex/case14 soln     $1
wit-test-case cplex/case15 opt-prt  $1
wit-test-case cplex/case16 opt-prt  $1
wit-test-case cplex/case17 opt-prt  $1
wit-test-case cplex/case18 opt-prt  $1
wit-test-case cplex/case19 soln     $1
wit-test-case cplex/case20 soln     $1
wit-test-case cplex/case20 crit     $1
wit-test-case cplex/case21 soln     $1
wit-test-case cplex/case22 soln     $1
wit-test-case cplex/case23 soln     $1
wit-test-case cplex/case24 soln     $1
wit-test-case cplex/case25 soln     $1
wit-test-case cplex/case26 soln     $1
wit-test-case cplex/case27 opt-prt  $1
