#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-case-run
#
# Runs the WIT stand-alone executable for test purposes.
#
# Parameters:
#    $1: The subdirectory of $WIT_HOME/wit-sa-test/data in which the input
#        data file, wit.data, is to be found.
#    $2: The stem of the name of the parameters file.
#        The parameters file will be at: $WIT_HOME/wit-sa-test/params/$2.par
#
# The output files will be placed in the following directory:
#     $WIT_HOME/wit-sa-test/data/$1/$2/output-new
#
# The output directory will be newly created, deleting any existing directory
# with that name.
# The stdout stream is redirected to /dev/null, since its content is a subset
# of the WIT log file.
#------------------------------------------------------------------------------

PARAM_FILE=$WIT_HOME/wit-sa-test/params/$2.par

if [ ! -f $PARAM_FILE ]
then

   echo "ERROR:"
   echo "   The paramater file"
   echo "   $PARAM_FILE"
   echo "   does not exist."

   exit

fi

DATA_DIR=$WIT_HOME/wit-sa-test/data/$1

if [ ! -d $DATA_DIR ]
then

   echo "ERROR:"
   echo "   The data directory"
   echo "   $DATA_DIR"
   echo "   does not exist."
   exit

fi

cd $DATA_DIR

if [ ! -d $2 ]
then

   rm $2 2> /dev/null

   mkdir $2

fi

cd $2

rm -r output-new 2> /dev/null

mkdir output-new
cd    output-new

cp $PARAM_FILE .

$WIT_HOME/wit/linux/wit $2.par > /dev/null 2> stderr.txt
