#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-lead-time-bds
#
# Performs the WIT lead time bounds test, unless $1 = "save".
# If $1 = "save", this script saves the results of the lead time bounds test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Lead Time Bounds" $1

wit-test-case lead-time-bds/case1  heur-spl3 $1
wit-test-case lead-time-bds/case2  heur-spl3 $1
wit-test-case lead-time-bds/case3  heur-spl3 $1
wit-test-case lead-time-bds/case4  heur-spl3 $1
wit-test-case lead-time-bds/case5  heur-spl3 $1
wit-test-case lead-time-bds/case6  heur-spl3 $1
wit-test-case lead-time-bds/case7  heur-spl3 $1
wit-test-case lead-time-bds/case9  heur-spl3 $1
wit-test-case lead-time-bds/case10 heur-spl3 $1
wit-test-case lead-time-bds/case11 heur-spl3 $1
wit-test-case lead-time-bds/case12 heur-spl3 $1
wit-test-case lead-time-bds/case13 heur-spl3 $1
wit-test-case lead-time-bds/case14 heur-spl3 $1
wit-test-case lead-time-bds/case15 heur-spl3 $1
wit-test-case lead-time-bds/case16 heur-spl3 $1
wit-test-case lead-time-bds/case17 heur-spl3 $1
wit-test-case lead-time-bds/case18 heur-spl3 $1
wit-test-case lead-time-bds/case19 heur-spl3 $1
wit-test-case lead-time-bds/case20 heur-spl3 $1
wit-test-case lead-time-bds/case21 heur-spl3 $1
wit-test-case lead-time-bds/case22 heur-spl3 $1
wit-test-case lead-time-bds/case23 heur-spl3 $1
wit-test-case lead-time-bds/case24 heur-spl3 $1
wit-test-case lead-time-bds/case25 heur-spl3 $1
wit-test-case lead-time-bds/case26 heur-spl3 $1
