#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-asap
#
# Performs the WIT ASAP build-ahead test, unless $1 = "save".
# If $1 = "save", this script saves the results of the ASAP build-ahead test.
#------------------------------------------------------------------------------

wit-test-cap-heading "ASAP Build-Ahead" $1

wit-test-case asap/case01 heur-spl3 $1
wit-test-case asap/case02 heur-spl3 $1
wit-test-case asap/case03 heur-spl3 $1
wit-test-case asap/case04 heur-spl3 $1
wit-test-case asap/case05 heur-spl3 $1
wit-test-case asap/case06 heur-spl3 $1
wit-test-case asap/case07 heur-spl3 $1
wit-test-case asap/case08 heur-spl3 $1
wit-test-case asap/case09 heur-spl3 $1
wit-test-case asap/case10 heur-spl3 $1
wit-test-case asap/case11 heur-spl3 $1
wit-test-case asap/case12 heur-spl3 $1
wit-test-case asap/case13 heur-spl3 $1
wit-test-case asap/case14 heur-spl3 $1
wit-test-case asap/case15 heur-spl3 $1
wit-test-case asap/case16 heur-spl3 $1
wit-test-case asap/case17 heur-spl3 $1
wit-test-case asap/case18 heur-spl3 $1
wit-test-case asap/case19 heur-spl3 $1
wit-test-case asap/case20 heur-spl3 $1
wit-test-case asap/case21 heur-spl3 $1
wit-test-case asap/case22 heur-spl3 $1
wit-test-case asap/case23 heur-spl3 $1
wit-test-case asap/case24 heur-spl3 $1
wit-test-case asap/case25 heur-spl3 $1
wit-test-case asap/case26 heur-spl3 $1
wit-test-case asap/case27 heur-spl3 $1
wit-test-case asap/case28 heur-spl3 $1
wit-test-case asap/case29 heur-spl3 $1
