#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-old-stock-re
#
# Performs the WIT old stock reallocation test, unless $1 = "save".
# If $1 = "save", this script saves the results of the old stock reallocation
# test.
#
# While all of these test cases were originally designed for the old stock
# reallocation algorithm, most of them have been modified to invoke the current
# (selective stock reallocation) algorithm. However, some of them still invoke
# the old algorithm.
#------------------------------------------------------------------------------

wit-test-cap-heading "Old Stock Reallocation" $1

wit-test-case old-stock-re/case01 heur-spl3 $1
wit-test-case old-stock-re/case02 heur-spl3 $1
wit-test-case old-stock-re/case03 heur-spl3 $1
wit-test-case old-stock-re/case04 heur-spl3 $1
wit-test-case old-stock-re/case05 heur-spl3 $1
wit-test-case old-stock-re/case06 heur-spl3 $1
wit-test-case old-stock-re/case07 heur-spl3 $1
wit-test-case old-stock-re/case08 heur-spl3 $1
wit-test-case old-stock-re/case09 heur-spl3 $1
wit-test-case old-stock-re/case10 heur-spl3 $1
wit-test-case old-stock-re/case11 heur-spl3 $1
wit-test-case old-stock-re/case12 heur-spl3 $1
wit-test-case old-stock-re/case13 heur-spl3 $1
wit-test-case old-stock-re/case14 heur-spl3 $1
wit-test-case old-stock-re/case15 heur-spl3 $1
wit-test-case old-stock-re/case16 heur-spl3 $1
wit-test-case old-stock-re/case17 heur-spl3 $1
wit-test-case old-stock-re/case18 heur-spl3 $1
wit-test-case old-stock-re/case19 heur-spl3 $1
wit-test-case old-stock-re/case20 heur-spl3 $1
wit-test-case old-stock-re/case21 heur-spl3 $1
