#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-multi-obj-coin
#
# Performs the WIT multiple objectives with COIN test, unless $1 = "save".
# If $1 = "save", this script saves the results of the multiple objectives
# with COIN test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Multiple Objectives with COIN" $1

wit-test-case multi-obj/case04 coin    $1
wit-test-case multi-obj/case10 coin    $1
wit-test-case multi-obj/case11 coin    $1
wit-test-case multi-obj/case12 coin    $1
wit-test-case multi-obj/case13 coin    $1
wit-test-case multi-obj/case14 coin    $1
wit-test-case multi-obj/case15 coin    $1
wit-test-case multi-obj/case16 coin    $1
wit-test-case multi-obj/case17 coin    $1
wit-test-case multi-obj/case19 coin    $1
