#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-sel-rec
#
# Performs the WIT selection recovery test, unless $1 = "save".
# If $1 = "save", this script saves the results of the selection recovery test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Selection Recovery" $1

wit-test-case sel-rec/case2  heur-spl3 $1
wit-test-case sel-rec/case3  heur-spl3 $1
wit-test-case sel-rec/case4  heur-spl3 $1
wit-test-case sel-rec/case5  heur-spl3 $1
wit-test-case sel-rec/case6  heur-spl3 $1
wit-test-case sel-rec/case7  heur-spl3 $1
wit-test-case sel-rec/case8  heur-spl3 $1
wit-test-case sel-rec/case9  heur-spl3 $1
wit-test-case sel-rec/case10 heur-spl3 $1
wit-test-case sel-rec/case11 heur-spl3 $1
wit-test-case sel-rec/case12 heur-spl3 $1
wit-test-case sel-rec/case13 heur-spl3 $1
wit-test-case sel-rec/case14 heur-spl3 $1
wit-test-case sel-rec/case15 heur-spl3 $1
wit-test-case sel-rec/case16 heur-spl3 $1
