#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-nstn
#
# Performs the WIT NSTN build-ahead test, unless $1 = "save".
# If $1 = "save", this script saves the results of the NSTN build-ahead test.
#------------------------------------------------------------------------------

wit-test-cap-heading "NSTN Build-Ahead" $1

wit-test-case nstn/case01      heur-spl3 $1
wit-test-case nstn/case02      heur-spl3 $1
wit-test-case nstn/case03      heur-spl3 $1
wit-test-case nstn/case04      heur-spl3 $1
wit-test-case nstn/case05      heur-spl3 $1
wit-test-case nstn/case06      heur-spl3 $1
wit-test-case nstn/case07.1    heur-spl3 $1
wit-test-case nstn/case07.2    heur-spl3 $1
wit-test-case nstn/case07.3    heur-spl3 $1
wit-test-case nstn/case07.4    heur-spl3 $1
wit-test-case nstn/case08      heur-spl3 $1
wit-test-case nstn/case08-asap heur-spl3 $1
wit-test-case nstn/case09      heur-spl3 $1
wit-test-case nstn/case10      heur-spl3 $1
wit-test-case nstn/case11      heur-spl3 $1
wit-test-case nstn/case12      heur-spl3 $1
wit-test-case nstn/case13      heur-spl3 $1
wit-test-case nstn/case14      heur-spl3 $1
wit-test-case nstn/case15      heur-spl3 $1
wit-test-case nstn/case16      heur-spl3 $1
wit-test-case nstn/case17      heur-spl3 $1
wit-test-case nstn/case18      heur-spl3 $1
wit-test-case nstn/case19      heur-spl3 $1
wit-test-case nstn/case20      heur-spl3 $1
