#!/bin/sh

#------------------------------------------------------------------------------
# Script wit-test-coin
#
# Performs the WIT COIN invocation test, unless $1 = "save".
# If $1 = "save", this script saves the results of the COIN invocation test.
#------------------------------------------------------------------------------

wit-test-cap-heading "COIN Invocation" $1

wit-test-case coin/case1  heur-opt $1
wit-test-case coin/case1  soln     $1
wit-test-case coin/case1  crit     $1
wit-test-case coin/case1  mps      $1
wit-test-case coin/case2  soln     $1
wit-test-case coin/case3  soln     $1
wit-test-case coin/case4  soln     $1
wit-test-case coin/case5  soln     $1
wit-test-case coin/case6  opt-prt  $1
