#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-all
#
# Performs the WIT Stand-Alone Test, unless $1 = "save".
# If $1 = "save", this script saves the results of the WIT Stand-Alone Test.
#
# This script is implemented for the linux platform only.
#------------------------------------------------------------------------------

if [ "$PLATFORM" != "linux" ]
then

   echo
   echo "ERROR: Script wit-test-all was invoked with PLATFORM=$PLATFORM."
   echo "       This script is implemented for the linux platform only."
   echo
   echo "Script aborted."
   echo

   exit

fi

wit-test-multi-route     $1
wit-test-nstn            $1
wit-test-asap            $1
wit-test-multi-exec      $1
wit-test-old-stock-re    $1
wit-test-sel-stock-re    $1
wit-test-prop-rtg        $1
wit-test-pen-exec        $1
wit-test-sel-split       $1
wit-test-pen-exec-split  $1
wit-test-sgl-src         $1
wit-test-sel-rec         $1

wit-test-stock-bds       $1
wit-test-two-lev-lot     $1
wit-test-user-heur-start $1
wit-test-con-peg         $1
wit-test-pgd-crit        $1
wit-test-heur-search-inc $1
wit-test-lead-time-bds   $1

wit-test-int             $1
wit-test-scrap           $1
wit-test-stoch           $1
wit-test-multi-obj       $1
wit-test-cplex           $1

wit-test-ship-late       $1
wit-test-pip             $1
wit-test-pip-opo         $1
wit-test-misc            $1
