#!/bin/ksh

#------------------------------------------------------------------------------
# Script wit-test-con-peg
#
# Performs the WIT concurrent pegging test, unless $1 = "save".
# If $1 = "save", this script saves the results of the concurrent pegging test.
#------------------------------------------------------------------------------

wit-test-cap-heading "Concurrent Pegging" $1

wit-test-case con-peg/case1 heur-soln $1
wit-test-case con-peg/case2 heur-soln $1
wit-test-case con-peg/case3 heur-soln $1
wit-test-case con-peg/case4 heur-soln $1
wit-test-case con-peg/case5 heur-soln $1
wit-test-case con-peg/case6 heur-soln $1
