#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script build-witj-cpp
#
# Builds the WIT-J C++ native library.
# Passes all arguments to make.
#------------------------------------------------------------------------------

echo
echo "Building the WIT-J C++ Native Library."
echo

cd $WIT_HOME/witj/cpp/$PLATFORM

make exe_type=released $* all

echo
echo "Build complete."
echo
