#!/bin/sh

#-----------------------------------------------------------------------------
# Sh Script build-witj-partlister
#
# Builds the example WIT-J application program PartLister:
#
# CDs to the partlister directory.
#
# Removes the WitJPartLister class file, if there is one.
#
# Compiles the WitJPartLister class.
#    The classpath consists of the WIT-J/Java Jar file.
#
# Copies the WIT-J Jar file to the name witj-partlister.jar.
#
# Invokes the jar command in update mode on witj-partlister.jar to do the
# following:
#    Add the WitJPartLister class file to it.
#    Specify class WitJPartLister as the entry point for the Jar file.
#
# When this script completes, witj-partlister.jar has the following properties:
#    It contains the WIT-J/Java     class files.
#    It contains the WitJPartLister class file.
#    It indicates class WitJPartLister as its entry point.
#    It is sealed. (This is from witj-jar.)
#-----------------------------------------------------------------------------

cd $WIT_HOME/witj/examples/partlister

rm -r WitJPartLister.class 2> /dev/null

#-----------------------------------------------------------------------------

$JAVA_HOME/bin/javac                                \
   -classpath $WIT_HOME/witj/java/bytecode/witj.jar \
   -Xlint                                           \
    WitJPartLister.java                             \

if [ ! -f WitJPartLister.class ]
then

   echo
   echo "Compilation of WIT-J PartLister has failed."
   echo
   exit
fi

echo
echo    "Compilation of WIT-J PartLister was successful."
echo

#-----------------------------------------------------------------------------

cp $WIT_HOME/witj/java/bytecode/witj.jar witj-partlister.jar

$JAVA_HOME/bin/jar uv0fe \
   witj-partlister.jar   \
   WitJPartLister        \
   WitJPartLister.class  \

echo "witj-partlister.jar has been created."
echo
