#!/bin/sh

#-----------------------------------------------------------------------------
# Sh Script build-witj-demo1
#
# Builds the example WIT-J application program Demo1:
#
# CDs to the demo1 directory.
#
# Removes the WitJDemo1 class file, if there is one.
#
# Compiles the WitJDemo1 class.
#    The classpath consists of the WIT-J/Java Jar file.
#
# Copies the WIT-J Jar file to the name witj-demo1.jar.
#
# Invokes the jar command in update mode on witj-demo1.jar to do the following:
#    Add the WitJDemo1 class file to it.
#    Specify class WitJDemo1 as the entry point for the Jar file.
#
# When this script completes, witj-demo1.jar has the following properties:
#    It contains the WIT-J/Java class files.
#    It contains the WitJDemo1  class file.
#    It indicates class WitJDemo1 as its entry point.
#    It is sealed. (This is from witj-jar.)
#-----------------------------------------------------------------------------

cd $WIT_HOME/witj/examples/demo1

rm -r WitJDemo1.class 2> /dev/null

#-----------------------------------------------------------------------------

$JAVA_HOME/bin/javac                                \
   -classpath $WIT_HOME/witj/java/bytecode/witj.jar \
   -Xlint                                           \
    WitJDemo1.java                                  \

if [ ! -f WitJDemo1.class ]
then

   echo
   echo "Compilation of WIT-J Demo1 has failed."
   echo
   exit
fi

echo
echo    "Compilation of WIT-J Demo1 was successful."
echo

#-----------------------------------------------------------------------------

cp $WIT_HOME/witj/java/bytecode/witj.jar witj-demo1.jar

$JAVA_HOME/bin/jar uv0fe \
   witj-demo1.jar        \
   WitJDemo1             \
   WitJDemo1.class       \

echo "witj-demo1.jar has been created."
echo
