#!/bin/sh

#-----------------------------------------------------------------------------
# Sh Script build-witj-tester
#
# Builds the WIT-J Tester, the java program that performs tests on WIT-J.
#
# CDs to the test directory.
#
# Removes the old bytecode directory, if any, creates a new one, and CDs to it.
#
# Compiles the Tester class of the witj.test package, which causes all other
# classes in the package to be compiled.
# The classpath includes the WIT-J Jar file.
#
# Copies the WIT-J Jar file to the name witj-test.jar.
#
# Invokes the jar command in update mode on witj-test.jar to do the following:
#    Add the class files for the WIT-J Tester to it.
#    Specify class Tester as the entry point for the Jar file.
#
# When this script completes, witj-test.jar has the following properties:
#    It contains the WIT-J/Java   class files.
#    It contains the WIT-J Tester class files.
#    It indicates class Tester as its entry point.
#    It is sealed. (This is from witj-jar.)
#-----------------------------------------------------------------------------

cd $WIT_HOME/witj/test

rm -r bytecode 2> /dev/null

mkdir bytecode

cd    bytecode

#-----------------------------------------------------------------------------

$JAVA_HOME/bin/javac                        \
   -sourcepath ../src                       \
   -classpath  ../../java/bytecode/witj.jar \
   -d          .                            \
   -Xlint                                   \
   ../src/com/ibm/witj/test/Tester.java     \

if [ ! -f com/ibm/witj/test/Tester.class ]
then

   echo
   echo "Compilation of WIT-J Tester has failed."
   echo
   exit
fi

echo
echo    "Compilation of WIT-J Tester was successful."
echo

#-----------------------------------------------------------------------------

cp $WIT_HOME/witj/java/bytecode/witj.jar witj-test.jar

$JAVA_HOME/bin/jar uv0fe    \
   witj-test.jar            \
   com.ibm.witj.test.Tester \
   com/ibm/witj/test        \

echo "witj-test.jar has been created."
echo
