#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script clean-witj-cpp
#
# Runs make clean on the WIT-J C++ object code.
#------------------------------------------------------------------------------

echo
echo "Make clean on the WIT-J C++ object code."
echo

cd $WIT_HOME/witj/cpp/$PLATFORM

make clean
