#!/bin/sh

#------------------------------------------------------------------------------
# Sh Script depend-witj-cpp
#
# Runs make depend on the WIT-J C++ source code.
#------------------------------------------------------------------------------

echo
echo "Make depend on the WIT-J C++ source code."
echo

cd $WIT_HOME/witj/cpp/$PLATFORM

make depend
