#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script time-witj
#
# Performs a timing test of WIT-J.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/test/data

$JAVA_HOME/bin/java                                 \
   -Djava.library.path=$WIT_HOME/witj/cpp/$PLATFORM \
   -enableassertions                                \
   -jar $WIT_HOME/witj/test/bytecode/witj-test.jar  \
    timing-test $1 $2 $3 $4 $5 $6                   \
