#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script witj-error-case
#
# Runs an error test on WIT-J for the case given in the argument.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/test/data

$JAVA_HOME/bin/java                        \
   -Djava.library.path=../../cpp/$PLATFORM \
   -enableassertions                       \
   -jar ../bytecode/witj-test.jar          \
    error-test $1                          \

if [ ! -f ErrTester.output ]
then
   exit
fi

echo                                  >> error-new.output
echo "------------------------------" >> error-new.output
echo " Contents of ErrTester.output " >> error-new.output
echo "------------------------------" >> error-new.output

cat ErrTester.output >> error-new.output
rm  ErrTester.output

