#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script witj-demo1
#
# Runs the example WIT-J application program Demo1.
#
# CDs to the demo1 directory.
#
# Runs the Demo1 program, witj-demo1.jar:
# * The Native Library Path is given as the directory that contains the
#   WIT-J/C++ native library.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/examples/demo1

$JAVA_HOME/bin/java                                \
  -Djava.library.path=$WIT_HOME/witj/cpp/$PLATFORM \
  -enableassertions                                \
  -jar witj-demo1.jar                              \
