#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script witj-error-test
#
# Performs the terminal error tests for WIT-J.
# Compares the output to the output of a previous run of the tests.
#
# Cases 6, 7, and 8 are skipped: They deliberately exhaust memory, which can
# cause problems (e.g. core dumps) that are not practical for routine tests.
#
# On WinSDK, runs dos2unix on error-new.output before doing the compare.
#    This is done, because error.new-output has Windows line delimiters, whereas
#    error-saved.output has Unix line delimiters, because its line delimiters
#    are specified as "Binary" in RTC. RTC requires the "Binary" line
#    delimiter specification on this file, because it contains non-standard
#    characters.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/test/data

rm error-new.output   2> /dev/null

echo
echo "Running error tests for WIT-J."

#-------------------------------------------------------------------------------
# Error Tests
#-------------------------------------------------------------------------------

$WIT_HOME/witj/scripts/witj-error-case  1 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case  2 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case  3 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case  4 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case  5 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case  9 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 10 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 11 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 12 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 13 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 14 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 15 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 16 2>&1 | cat >> error-new.output
$WIT_HOME/witj/scripts/witj-error-case 17 2>&1 | cat >> error-new.output

#-------------------------------------------------------------------------------
# Compare
#-------------------------------------------------------------------------------

echo "Comparing error-new.output with error-saved.output."
echo

if [ $PLATFORM = "winsdk" ]
then

    dos2unix error-new.output

fi

diff                                                  \
   -I "^JVMDUMP"                                      \
   -I "^      java.library.path = "                   \
   -I "^      Offending string (as a Java String): S" \
   -I "^WIT0716I    Operation Name:            \"S"   \
   -I "ClassLoader\."                                 \
   -I "at java\.lang\..*\.loadLibrary"                \
   -I "00MB of memory have been allocated by WIT-J"   \
   -I "00MB of memory have been discarded."           \
                                                      \
   error-saved.output                                 \
   error-new.output                                   \
 > error-diff.output                                  \
