#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script witj-partlister
#
# Runs the example WIT-J application program PartLister.
#
# CDs to the partlister directory.
#
# Runs the PartLister program, witj-partlister.jar:
# * The Native Library Path is given as the directory that contains the
#   WIT-J/C++ native library.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/examples/partlister

$JAVA_HOME/bin/java                                \
  -Djava.library.path=$WIT_HOME/witj/cpp/$PLATFORM \
  -enableassertions                                \
  -jar witj-partlister.jar                         \
