#!/bin/sh

#-------------------------------------------------------------------------------
# Sh Script witj-thread-test
#
# Performs the thread test for WIT-J.
#
# CDs to the data directory.
#
# Removes the old thread-new.output file, if any.
#
# Runs the Tester with argument "thread-test".
# * The Java Class Path is given as:
#      the directory that contains the bytecode for the Tester and
#      the WIT-J/Java Jar file.
# * The Native Library Path is given as:
#      the directory that contains the WIT-J/C++ native library.
# * All output is directed to thread-new.output.
# This performs a thread test of WIT-J.
#
# Compares thread-new.output to thread-saved.output, storing the differences in
#    thread-diff.output.
#-------------------------------------------------------------------------------

cd $WIT_HOME/witj/test/data

rm thread-new.output 2> /dev/null

echo
echo "Running the thread tests for WIT-J."

#-------------------------------------------------------------------------------
# Thread Test
#-------------------------------------------------------------------------------

$JAVA_HOME/bin/java                        \
   -Djava.library.path=../../cpp/$PLATFORM \
   -enableassertions                       \
   -jar ../bytecode/witj-test.jar          \
    thread-test                            \
    2>&1 | cat >> thread-new.output        \

#-------------------------------------------------------------------------------
# Compare
#-------------------------------------------------------------------------------

echo "Comparing thread-new.output with thread-saved.output."
echo

diff                   \
   thread-saved.output \
   thread-new.output   \
 > thread-diff.output  \

